---
#- name: Get EC2 Facts
#  action: ec2_facts

  #- name: Set default private IP to node_ip
  #set_fact: private_ip="{{ node_ip }}"

  #- name: Set private IP var (AWS)
  #set_fact: private_ip="{{ ansible_default_ipv4.address  }}"
  #when: deployment_environment == "aws"

  #- name: Set private hostname var (AWS)
  #set_fact: private_hostname="{{ ansible_hostname }}"
  #when: deployment_environment == "aws"

  #- debug: var=private_ip
  #- debug: var=private_hostname

  #- name: Template seed list
  #template: src=seeds.j2 dest=/tmp/seed_list mode=0664

  #- name: Load seed list
  #shell: cat /tmp/seed_list
  #register: seed_list

  #- name: Set seeds fact
  #set_fact: seeds={{ seed_list.stdout }}

  #- debug: var=seeds

- name: Add Datastax repository (DCE)
  shell: echo "deb http://debian.datastax.com/community stable main" > /etc/apt/sources.list.d/cassandra.sources.list
  when: install_version == "dce"

- name: Add Datastax repository key
  shell: curl -L http://debian.datastax.com/debian/repo_key | apt-key add -

- name: Add Oracle Java PPA repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Oracle license (1/2)
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections"

- name: Accept Oracle license (2/2)
  shell: "echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections"

- name: Update APT cache
  apt: update_cache=true

- name: Install python-software-properties package
  apt: pkg=python-software-properties state=present

- name: Install python-setuptools package
  apt: pkg=python-setuptools state=present

- name: Install Oracle Java
  apt: name=oracle-java8-installer state=latest
