---
# Variables that can provide as extra vars
VPC_NAME: Cassandra-VPC2
VPC_REGION: us-west-2 # Oregon
EC2_INSTANCE_TYPE: t2.micro
EC2_KEY_NAME: "qdp-poc"
EC2_SECURITY_GROUP_NAME: "default"
EC2_COUNT: 1
EC2_VOLUME_SIZE: 10
EC2_SUBNET_ID: []
# Example of EC2_SUBNET_ID
# EC2_SUBNET_ID:
#   - "subnet-0c3e0b7b"
#   - "subnet-bf672ae6"
AMI_NAME: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
AMI_OWNER: "099720109477"

# Tags
ENVIRONMENT: test
SERVER_ROLE: test

# Use inside the tasks
vpc_name: "{{ VPC_NAME }}"
vpc_region: "{{ VPC_REGION }}"
ec2_instance_type: "{{ EC2_INSTANCE_TYPE }}"
ec2_key_name: "{{ EC2_KEY_NAME }}"
ec2_security_group_name: "{{ EC2_SECURITY_GROUP_NAME }}"
ec2_volume_size: "{{ EC2_VOLUME_SIZE }}"
ec2_count: "{{ EC2_COUNT }}"
ec2_subnet_id: "{{ EC2_SUBNET_ID }}"

ami_name: "{{ AMI_NAME }}"
ami_owner: "{{ AMI_OWNER }}"
